version: '3'
services:
  backend:
    build:  ./app-peliculas-backend/apip-peliculas-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - TMDB_API_KEY=${TMDB_API_KEY}
    restart: always
    container_name: cometa-backend
  frontend:
    build: ./app-peliculas-frontend/app-frontend-cometafilms
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    container_name: cometa-frontend
